### ISSUE TITLE
Feature Request: Quick Toggle All Turrets

### ISSUE THREAD

**Issue by Gwindalmir** [TorchAPI/Essentials#1]
I think an option to quick toggle all turrets on/off would be nice for server management (and scenario set-ups).

Something like toggle all World/Grid/Faction/Player turrets, and have essentials remember which ones it actually changed, so when you toggle back, player set turrets don't get changed.

**Comment by Varaxian** [comment]
TBH, this is quite useful in old SESE functionality with all block types. /off (BlockTypeID) lets me figure out who's being a dumba$$ (most of the time its projectors, PBs, sorters or drills) 

<3
