### ISSUE TITLE
!entities refresh broken by today's SE update

### ISSUE THREAD

**Issue by Jimmacle** [TorchAPI/Essentials#11]
Check the reflection, I have a feeling something in the replication layer changed.

**Comment by Equinox-** [comment]
Fixed in da1b36f38b204b42aead1f0334c786ff5195116c.
Available in [staging](http://torchapi.net:8080/job/Torch/job/Essentials/job/staging/); requires [Torch staging](http://torchapi.net:8080/job/Torch/job/Torch/job/staging/).
