### ISSUE TITLE
Request: !admin playerlist should also show playerID and steamID

### ISSUE THREAD

**Issue by LordTylus** [TorchAPI/Essentials#111]
Hello there,

sometimes I need to look something up in the save file or add a player to some config files via Steam ID.

For that it would be hugely helpful when the player list not only shows the currently online players but also their identification, like the entity ID and steam ID.

Because otherwise the whole command is not really that useful as you can see all currently online players in the Server UI and ingame via F3 screen.

**Comment by N1Ran** [comment]
This is simple to add.

**Comment by N1Ran** [comment]
Done
