### ISSUE TITLE
Feature Request: Invisibility and Admin Log

### ISSUE THREAD

**Issue by DanMcgraw** [TorchAPI/Essentials#114]
I was wondering if it were possible to add the following features to this plugin:
Invisibility, so admins can ghost as a player but not visible to others, god mode and non-targetable simultaneously.

Admin log, a log file that specifically logs placed blocks in creative, and pasted blueprints and spawned items, to detect corrupt admins that are cheating. Also logging player teleports and such, to ensure that admins who are playing the game are not cheating.

**Comment by bodyboarder2528** [comment]
There is a plugin for admin logging https://torchapi.net/plugins/item/610d6b05-94a0-4bb1-845c-e6c848115171

**Comment by N1Ran** [comment]
This issue can be closed.
