### ISSUE TITLE
Feature Request: Essentials Save/Commit Button

### ISSUE THREAD

**Issue by RealRogueCmdr** [TorchAPI/Essentials#115]
Please add a Save or Commit change type button for when adding or making changes to auto command. Doing a Add/Remove just to commit changes is problematic and being an IT System Engineer isnt logical. Ive made changes and found some that dont get commited and have to go reapply them, this causes downtime or server issues as autocommands are not being ran when commited/expected.

**Comment by rexxar-tc** [comment]
No.

**Comment by RealRogueCmdr** [comment]
i was told to add this in github the other day
