### ISSUE TITLE
Feature request: Saving deleted grids.

### ISSUE THREAD

**Issue by CommanderPirx** [TorchAPI/Essentials#118]
Would it be possible to make an option in Essentials that when toggled would save every grid deleted with !cleanup to the server files (in same way the !export command does it)? And then perhaps it would also remove files older than set age (like default 3 days for example) from the folder that those grids would be saved in, so that the storage isn't filled with old removed grids. 

The reasoning behind this feature being an ability to bring back grids automatically removed with various auto cleanup, because sometimes grids are made eligible for those cleanups by accident, and then players want them back. This proposed feature would make that easy. (especially along with another one I've proposed, logging deleted grid owner names - https://github.com/TorchAPI/Essentials/issues/117)

**Comment by foogs** [comment]
in keen blueprint format pls

**Comment by N1Ran** [comment]
Use Hangar plugin
