### ISSUE TITLE
Torch crashes after clicking on autocommand enable checkbox

### ISSUE THREAD

**Issue by fr33soul** [TorchAPI/Essentials#12]
If i click on enable checkbox, Torch crashes.

**Comment by szczepix** [comment]
Yep, please fix or temporary disable that checkbox. Same things with text input.

**Comment by Jimmacle** [comment]
If you know it's broken don't use it, I'm working on a massive overhaul of that system right now.

**Comment by szczepix** [comment]
right

**Comment by fr33soul** [comment]
anyway i wish to trigger a restart command, is it possible to add it manually to its cfg file? how?

**Comment by szczepix** [comment]
@fr33soul 
Example:
```xml
<AutoCommand>
	<Enabled>true</Enabled> <!-- true or false -->
	<Command>!say More info about us you can find on
        www.rebels-games.com</Command> <!-- command/text - one or multiline -->
	<DueTime>600</DueTime> <!-- after server start in seconds -->
	<Period>3300</Period> <!-- repeat every in seconds -->
</AutoCommand>

**Comment by Jimmacle** [comment]
Fixed in current staging because it's taking longer to make the new system than I anticipated.
