### ISSUE TITLE
World won't load with Torch Installed

### ISSUE THREAD

**Issue by Forbiddenuk** [TorchAPI/Essentials#124]
Having issues running server since Torch update. Server world won't load up with Torch installed. Server world loads up fine without Torch. Happened once we removed profiler and updated torch to .72

[Torch-2019-08-25.log](https://github.com/TorchAPI/Essentials/files/3538457/Torch-2019-08-25.log)

**Comment by Jimmacle** [comment]
It looks like one of the plugin zip files may be corrupt. Delete them and start the server, it should download fresh copies automatically.

**Comment by Forbiddenuk** [comment]
Seems to have been the problem, thanks. Per LordTylus:  it would be nice if torch had error handling for that like
ohh plugin is broken, and available on the official website, so just download it anew
otherwise tell the user which plugin had issues loading

**Comment by LordTylus** [comment]
You didnt need to quote me on every word there...

**Comment by rexxar-tc** [comment]
Fixed in patron branch
