### ISSUE TITLE
Need a GUI field to edit PiratePCU

### ISSUE THREAD

**Issue by horatio42** [TorchAPI/Essentials#125]
Need a GUI entry to modify the PiratePCU value in the Sandbox.sbc file

It defaults to PiratePCU>50000</PiratePCU>

every time, and the number being that low seems to break the NPC shops ability to spawn ships in some cases.

Can't edit it by hand, since Torch just auto-sets it back to 50,000

**Comment by LordTylus** [comment]
That would not be an essentials issue though.

but a very appriciated feature :-)

**Comment by horatio42** [comment]
I'm an idiot. It was late and I wasn't paying attention to where I put this. I'll close this and put a new one where it belongs.
