### ISSUE TITLE
Server don't want to start. 

### ISSUE THREAD

**Issue by SpaceHolly** [TorchAPI/Essentials#126]
[Torch-2019-08-28 (1).log](https://github.com/TorchAPI/Essentials/files/3552161/Torch-2019-08-28.1.log)
[Torch-2019-08-28 (2).log](https://github.com/TorchAPI/Essentials/files/3552162/Torch-2019-08-28.2.log)
[Torch-2019-08-28.log](https://github.com/TorchAPI/Essentials/files/3552163/Torch-2019-08-28.log)
[Keen-2019-08-28 (1).log](https://github.com/TorchAPI/Essentials/files/3552164/Keen-2019-08-28.1.log)
[Keen-2019-08-28 (2).log](https://github.com/TorchAPI/Essentials/files/3552165/Keen-2019-08-28.2.log)
[Keen-2019-08-28.log](https://github.com/TorchAPI/Essentials/files/3552166/Keen-2019-08-28.log)
I just want it to run. But it won't. Please fix it somehow.

**Comment by smooreace** [comment]
Ditch all the mods and I bet it starts. Im not going to read through all
the logs, but your problem isnt Torch related. Its your world.

**Comment by SpaceHolly** [comment]
I tried to delete ALL mods I even reinstall Torch, nothing helped.

**Comment by Fuski528** [comment]
Have you tried to update/made sure the Visual C++ are uptodate?

**Comment by SpaceHolly** [comment]
Yes.

**Comment by SpaceHolly** [comment]
Microsoft NET was also up to date

**Comment by SpaceHolly** [comment]
Found a problem: This server needs EXACTLY same IP with computer. "Torch" don't search for IP.
