### ISSUE TITLE
Feature Request: !uptime  command

### ISSUE THREAD

**Issue by franky500** [TorchAPI/Essentials#14]
An !uptime command or similar to show how long the server has been up for so far, Useful for automatic restarts on servers that let users know how often restarts are scheduled for users to check how long is left until the next restart.

**Comment by szczepix** [comment]
I've created that issue in Torch: https://github.com/TorchAPI/Torch/issues/83

**Comment by franky500** [comment]
i guess i should have checked through torch issues first!  My thought track was, Essentials manages auto commands, essential can manage the !uptime, but it does make more sense as a torch command since thats where the uptime would come from.
