### ISSUE TITLE
[Suggestion] Add Voxel maps revert on planets with distance parameter.

### ISSUE THREAD

**Issue by dorimanx** [TorchAPI/Essentials#144]
Idea to use KEEN way to cleanup holes in planet voxels by using commands with distance check.

Something like this:
!voxels reset all playesrdistance 10000 gridsdistance 100
This will restore/cover all the holes in voxel but will not crash clients, as cleanup done not in range of the SYNC with player.
KEEN method is using these configs, it's may help to find how all done:

SyncDistance>4000</SyncDistance

VoxelTrashRemovalEnabled>true</VoxelTrashRemovalEnabled
VoxelPlayerDistanceThreshold>7000</VoxelPlayerDistanceThreshold
VoxelGridDistanceThreshold>50</VoxelGridDistanceThreshold
VoxelAgeThreshold>10</VoxelAgeThreshold

Distance in meters!
Age in minutes.

Thank you.

**Comment by rexxar-tc** [comment]
Keen's voxel revert doesn't work the way you think it does. It is not useful to us.
