### ISSUE TITLE
[Bug] !grids static large does not work

### ISSUE THREAD

**Issue by Jentara** [TorchAPI/Essentials#25]
Just returns the command back into chat.  Nothing changes.  Would also like to be a feature request that you could specify which grids by name.
Observed...if you have a large grid, and type the command.  The buttons in the info tab "Convert to ship" and "Convert to Station" stop working.  
Running the command !entities Refresh corrects it.

**Comment by rexxar-tc** [comment]
Fixed on feature-merge branch
