### ISSUE TITLE
how can i find out what commands do ? eg identity.clean & purge, parameters for cleanup?

### ISSUE THREAD

**Issue by zarozak** [TorchAPI/Essentials#26]
i know its in development but its hard to use with no information, hope you don't mind providing some basics

thanks

**Comment by szczepix** [comment]
https://github.com/TorchAPI/Essentials/wiki/Commands

https://github.com/TorchAPI/Essentials/wiki/Auto-Commands-Example

**Comment by theCalcaholic** [comment]
You can also type in the console `!longhelp` to get a list of commands and `!help <command>` to get information about a command.
