### ISSUE TITLE
[Bug] !entities find Timer = returns nothing

### ISSUE THREAD

**Issue by Jentara** [TorchAPI/Essentials#27]
Testing some find commands to locate timer blocks.  typing !entities find Timer returns:
Server: Found entities:

But has no results.
Using !entities find grid or cargo works, but many other things fail too
Have tried Timer, Antenna, Program. cyro ...all return nothing

so far only Cargo, Beacon, and Grid worked

btw - that is the latest Staging Essentials plugin

**Comment by theCalcaholic** [comment]
That's not how that command works according to the description. `!entities <string>` only searches for entity (i.e. grid or loose item) names, not block types.
To search for block types you need to use the cleanup command (e.g. `cleanup list hastype TimerBlock`)

**Comment by N1Ran** [comment]
This is a user error and not a bug.  Please close.  🤔  Could add a response for empty returns
