### ISSUE TITLE
no instructions?

### ISSUE THREAD

**Issue by zarozak** [TorchAPI/Essentials#3]
I have loaded it, along with torch and Concealment but sadly I don't see any instructions?
how do I set an motd?
what commands are available?
creating code is great but se users like myself need a little more than good code :) a hint on what it can do and how to use it would be nice

**Comment by Jimmacle** [comment]
I plan to document the project when it's nearly complete, otherwise I waste time documenting features and then re-documenting them when they change.

**Comment by zarozak** [comment]
How do I set an motd? 

Regards

Paul Sexstone

**Comment by XeroCreator** [comment]
@zarozak use this an an example it's my full essentials.cfg. the auto-command set happens every 30 minutes. to 'advertise' the motd command. 
the <motd> tags are where you would put your motd, this shows up when someone logs into your server. 
This is located in the servers instance location.

<?xml version="1.0"?>
<EssentialsConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <AutoCommands>
    <AutoCommand>
      <Enabled>true</Enabled>
      <Command>!say Type !motd for server info. To save your ships, be sure to place at least 1 Antenna on it, or the cleanup will delete it!</Command>
      <DueTime>1</DueTime>
      <Period>1800</Period>
    </AutoCommand>
    <AutoCommand>
      <Enabled>false</Enabled>
      <DueTime>0</DueTime>
      <Period>0</Period>
    </AutoCommand>
  </AutoCommands>
  <Motd>Welcome!
Please visit the discord and group for important information on the server!
Announcements (Join the group! ): 
Discord (Join for more status updates on the server!):
</Motd>
</EssentialsConfig>
