### ISSUE TITLE
Restart Commands

### ISSUE THREAD

**Issue by Symptomy** [TorchAPI/Essentials#30]
We installed Torch and Essentials on our server and it's running fine.  However, our automated restart is counting down every minute and I can't seem to find how to change the interval.  Is there some way the restart command could be outlined in the wiki?

**Comment by Jimmacle** [comment]
You can set the autocommand's DueTime in seconds to delay the command running, then just provide the length of the countdown you want to the restart command. I don't plan on documenting the current system because I'm going to replace it with something easier to use.

**Comment by Symptomy** [comment]
Yeah I can totally understand that.  Appreciate the response though.  I guess my issue is that I'm not quite sure how to input the command.  We're using: <Command>!restart 7200 true</Command> and I've tried implementing a few changes that have met with nothing but errors.

**Comment by Murllin** [comment]
in your essentials.cfg you should have a part that looks like this:

    <AutoCommand>
      <Enabled>true</Enabled>
      <Command>!restart 900</Command>
      <DueTime>1</DueTime>
      <Period>9900</Period>
    </AutoCommand>

The number after the restart is the actual timer that announces in the server. Thats why your getting a countdown every minute. Just set it to 900 for a 15 minute countdown. The <Perriod> will tell it when to actual trigger the countdown.

**Comment by Symptomy** [comment]
Okay so if I'm reading it right, the number after the !restart dictates when the countdown starts.  Right on.  Thanks.
