### ISSUE TITLE
Stop command need countdown too

### ISSUE THREAD

**Issue by foogs** [TorchAPI/Essentials#31]
Stop command need countdown like !restart.
And reason.
- [ ] `!stop [int countdown] [bool save] [string REASON]`
- [ ] `!restart [int countdown] [bool save] [string REASON]`

**Comment by szczepix** [comment]
And please add
- [ ] `!stop cancel`
- [ ] `!restart cancel`

**Comment by Ketyi85** [comment]
Hi Help me. How can I make Torch make every 2 hours a server restart?
