### ISSUE TITLE
[Feature request] Add ability to perform commands at specific time of day

### ISSUE THREAD

**Issue by MikeD1980** [TorchAPI/Essentials#34]
It would be really great to have Essentials perform commands at specific times of day.
Example, !save command at 05:50 and !stop at 05:55 before the system reboots itself at 06:00
a few times the server has rebooted during an autosave and corrupted the savegame - this would help avoid it. also handy for other commands but this would be my main use. Cheers.

**Comment by Jimmacle** [comment]
This is planned as part of the autocommands overhaul.

**Comment by MikeD1980** [comment]
Excellent, thanks

**Comment by Jimmacle** [comment]
Gonna close this issue since it's pretty much the same as the one referenced above, follow that one for updates.
