### ISSUE TITLE
[feature] Ability to enable / disable full chat

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Essentials#37]
I'd like to be able to see everything sent in chat from my members. Right now running frontier economy with / commands I don't see what they typed. I'd like a way to catch those to be displayed on torch chat or in a chatlog at minimum. SESE used to dump everything into chat and I could see any typing or command mistakes they were making and correct them in real time. Also I don't think admin run torch commands are being sent to the console either. Not everyone may not like this option so possibly a way to toggle the feature on/off to not clutter chat.

**Comment by Jimmacle** [comment]
This would require a client side mod that sends all entered messages to the server. I'm not saying no, but I don't currently have plans to make a mod for Essentials.

**Comment by rexxar-tc** [comment]
This issue was moved to TorchAPI/Torch#233
