### ISSUE TITLE
features-merge branch - crashes on player connect

### ISSUE THREAD

**Issue by horatio42** [TorchAPI/Essentials#41]
When players connect, doesn't seem to be any particular players, I get the following blurb in the log right before it crashes and auto restarts:

https://pastebin.com/4P75kYHF

**Comment by smooreace** [comment]
Fix your config. The plugin works great!

**Comment by horatio42** [comment]
Config file wasn't broken. I was using the wrong branch of torch apparently. Rexar set me straight.
