### ISSUE TITLE
Feature Merge - Broken AutoCommands

### ISSUE THREAD

**Issue by N1Ran** [TorchAPI/Essentials#42]
The autocommands no longer run under current feature merge.

**Comment by Murllin** [comment]
Ive run into this as well. Ive set the command line as "!restart 600"  and the delay time to 03:00:00. I assume this should run the command at 3 hours but so far it has not worked.

**Comment by smooreace** [comment]
It works fine. You are setting it up wrong

**Comment by N1Ran** [comment]
@smooreace We are speaking of the "Feature Merge" version.  The master works fine, Rex has a test version which current has the command broken and since the test is to be implemented to the masters later on, it's best to finalize all bugs/issues while in test

**Comment by smooreace** [comment]
!restart 300 true 10800 10800

That leads to a 3 hour restart with 5 minute warning and worldsave prior to restart

**Comment by smooreace** [comment]
In the essentials config it looks like...
```
<Command>!restart 300 true</Command>
      <DueTime>10800</DueTime>
      <Period>10800</Period>
```

**Comment by N1Ran** [comment]
Again, that is the master version. The "Feature Merge" version uses intervals i.e
    <AutoCommand>
      <Enabled>true</Enabled>
      <Command>!blocks off type GravityGenerator</Command>
      <InitialDelay>00:01:00</InitialDelay>
      <RepeatInterval>03:00:00</RepeatInterval>
    </AutoCommand>

**Comment by rexxar-tc** [comment]
Fixed in latest release.
