### ISSUE TITLE
[Feature Merge] Cleanup is up to no good again

### ISSUE THREAD

**Issue by N1Ran** [TorchAPI/Essentials#44]
Torch Version:v1.3.0.47-101-g94b457d

Plugins Loaded:
'Concealment' (v1.4.0.12-2-g731a58c)19:27:16.4106 
'Essentials' (v1.7.0.14-34-g58122b0)19:27:16.4606
'NoGrief' (v2.0.3.8)19:27:16.5376
'SEDiscordBridge' (v1.3.2)19:27:16.5626
'Torch Backup System' (v0.7.1.50)

Issue: Cleanup command is not finding the grids that meets argument
Example:
	World loaded with grids with no beacons
	"!cleanup scan" yields the amount of grids present (no problem)
	" !cleanup scan" notype Beacon
		Command yields 0 result
	"!cleanup delete/scan/list" all are affected by this issue
	"!cleanup scan" does yield all entities present, but will not work when an argument is added

All arguments affected by this problem

A secondary issue is the command at times will yield a small amount of grids that meets the argument but not all

**Comment by rexxar-tc** [comment]
Should be fixed in cf47d52
