### ISSUE TITLE
Feature Request: Factions Cleaning

### ISSUE THREAD

**Issue by Helidude** [TorchAPI/Essentials#47]
There should be a command to delete empty factions. 
Could also be linked to the !identity purge in some way. 

- Remove inactive players from faction, for example with !identity purge command
- Delete faction if empty

**Comment by Jimmacle** [comment]
Implemented 7d32d44c0afe1144a98d7a6399582f2dbc5cc254

**Comment by Helidude** [comment]
Doing "!identity purge 14" does not clean my empty factions. 
Is that the correct usage? 

My Sandbox.sbc might be a mess tho
