### ISSUE TITLE
Empty MotD causes crash on respawn

### ISSUE THREAD

**Issue by Chemsorly** [TorchAPI/Essentials#5]
After todays update my client crashed to main menu when I tried connecting to my dedicated. The crash occured when choosing a respawn location and pressing on respawn. The dedicated showed the following error message:

![image](https://user-images.githubusercontent.com/20582199/28632612-7dee03cc-7231-11e7-8632-b5f6c0c58792.png)

after I added a MotD that was not empty spawning did work. Looks like there's a nullcheck missing.

**Comment by Jimmacle** [comment]
Fixed d587e415298e14871bdfc2714276f11f744ae62a, version 1.5.1 has the fix.
