### ISSUE TITLE
request: !voxels reset planet center

### ISSUE THREAD

**Issue by XeroCreator** [TorchAPI/Essentials#56]
- [X] Is this a suggestion?
There is a 'clean planet center' command in essentials. 
I am requesting a command for (if possible) cleaning the center of a planet voxels of earth with a 5-10km range of 0,0,0. 
Not even sure if it's possible but just figured i'd write it down.

**Comment by Fowlplaychiken** [comment]
I believe anything more than 1/3 below planets surface gets deleted already - but voxel reset can do only the whole planet.

I had not noticed any voids inside the planet caused by grids going there however....

**Comment by N1Ran** [comment]
This already is a function with !cleanup delete...insideplanet
