### ISSUE TITLE
Request: Delete grids if OWNER has not logged in for X days

### ISSUE THREAD

**Issue by Fowlplaychiken** [TorchAPI/Essentials#58]
There is a vanilla cleanup feature, to delete grids if AUTHOR has not logged in for X hours. 
It is useless, because it is based on Authorship and not Ownership, and many servers do not have PCU limits enabled; so authorship can not be reassigned. 

I would love a torch feature to delete grids if owner has not logged in, in X hours/days. It would help clean my server significantly, of old unused grids.

**Comment by rexxar-tc** [comment]
the identity purge command does this
