### ISSUE TITLE
Triggered Commands (autocommands)

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Essentials#64]
Ability to define a triggered cleanup based on number of variables scanned in world. 
We need to be able to perform auto wreckage cleanups within a defined time after combat takes place to keep sim speeds up. As of right now servers need to be rebooted and a lot of manual cleanup commands need run after combat to make things actually work again. Big fights, sim speeds drops to .3 and never recovers if an admin is not present to run a cleanup command or server restart.

All we need is to be able to say if 20 grids have less then 20 blocks and no owner or no specific subtype is present then wait 5 minutes and delete them.

**Comment by N1Ran** [comment]
Hey Rexxar, Close this shit down 😉

**Comment by rexxar-tc** [comment]
Added on Patron branch.
