### ISSUE TITLE
Sandbox Clean/Faction Clean threw an exception

### ISSUE THREAD

**Issue by ghost** [TorchAPI/Essentials#66]
Hello, I found a bug with the commands `!sandbox clean` and `!faction clean "arg"`

Indeed the log shows me this when I try to use those commands 

> Log of sandbox clean

> 10:56:52.9932 [INFO]   Chat: Error (to Kurtz): Exception has been thrown by the target of an invocation.
> 10:56:52.9932 [ERROR]  Torch.Commands.Command: Command '!sandbox clean ' from 'Essentials' threw an exception. Args: 
> 10:56:52.9932 [ERROR]  Torch.Commands.Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetParameterCountException: Parameter count mismatch.
>    at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Torch.Managers.NetworkManager.RaiseEvent(MethodInfo method, Object obj, EndpointId endpoint, Object[] args) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\NetworkManager\NetworkManager.cs:line 343
>    at Essentials.Commands.WorldModule.RemoveFaction(MyFaction faction) in C:\Program Files (x86)\Jenkins\workspace\Torch_Essentials_master-7VGPHAWV6GZDCSKVXUROPZH72LPOY457A3FREZRQLZR6Q5CZPS3A\Essentials\Commands\WorldModule.cs:line 166
>    at Essentials.Commands.WorldModule.CleanFaction_Internal(Int32 memberCount) in C:\Program Files (x86)\Jenkins\workspace\Torch_Essentials_master-7VGPHAWV6GZDCSKVXUROPZH72LPOY457A3FREZRQLZR6Q5CZPS3A\Essentials\Commands\WorldModule.cs:line 130
>    at Essentials.Commands.WorldModule.CleanSandbox() in C:\Program Files (x86)\Jenkins\workspace\Torch_Essentials_master-7VGPHAWV6GZDCSKVXUROPZH72LPOY457A3FREZRQLZR6Q5CZPS3A\Essentials\Commands\WorldModule.cs:line 244
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Commands\Command.cs:line 145
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetParameterCountException: Parameter count mismatch.
>    at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Torch.Managers.NetworkManager.RaiseEvent(MethodInfo method, Object obj, EndpointId endpoint, Object[] args) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\NetworkManager\NetworkManager.cs:line 343
>    at Essentials.Commands.WorldModule.RemoveFaction(MyFaction faction) in C:\Program Files (x86)\Jenkins\workspace\Torch_Essentials_master-7VGPHAWV6GZDCSKVXUROPZH72LPOY457A3FREZRQLZR6Q5CZPS3A\Essentials\Commands\WorldModule.cs:line 166
>    at Essentials.Commands.WorldModule.CleanFaction_Internal(Int32 memberCount) in C:\Program Files (x86)\Jenkins\workspace\Torch_Essentials_master-7VGPHAWV6GZDCSKVXUROPZH72LPOY457A3FREZRQLZR6Q5CZPS3A\Essentials\Commands\WorldModule.cs:line 130
>    at Essentials.Commands.WorldModule.CleanSandbox() in C:\Program Files (x86)\Jenkins\workspace\Torch_Essentials_master-7VGPHAWV6GZDCSKVXUROPZH72LPOY457A3FREZRQLZR6Q5CZPS3A\Essentials\Commands\WorldModule.cs:line 244
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Commands\Command.cs:line 145
> 10:56:52.9932 [INFO]   Torch.Commands.CommandManager: Player Kurtz ran command '!sandbox clean'

I hope you will the issue, kind regards !

**Comment by SplenectomY** [comment]
Can also reproduce.

**Comment by rexxar-tc** [comment]
Should be fixed on Patron branch.
