### ISSUE TITLE
Command Scheduler Improvements

### ISSUE THREAD

**Issue by Jimmacle** [TorchAPI/Essentials#7]
Triggers:
- [x] Interval
- [x] Specific Time
- [ ] Grid created/destroyed
- [ ] Player joined/left
- [ ] Server started
- [ ] Server stopping
Triggers should provide information that can be supplied to commands.

Conditions:
- [ ] Grid count
- [ ] Player count
- [ ] Sim speed

**Comment by N1Ran** [comment]
And This one too.  Donzo!
