### ISSUE TITLE
Request: !cutpaste command

### ISSUE THREAD

**Issue by benjhook** [TorchAPI/Essentials#78]
Requesting a "!cutpaste gridname" command that can be enabled/disabled by admin, and if enabled, usable by any player on their own grids.

It should essentially do the same thing as when an admin manually cut/pastes a grid for a player, with a few safety checks in place to prevent the player from cutpasting a grid that intersects another grid, voxel, or character, and possibly a configurable per-player cooldown and max grid size cap if this has the potential to have a considerable performance impact on a server.

This feature would drastically reduce the amount of time an admin has to spend in game fixing bugged grids for players.

**Comment by SoContent** [comment]
Idk what to add. I support !unfuckit of target grid. Or however it gets done. If I learn to code and learn C# then maybe can do meself. ^_^

GL tho.. this would game changing, if players could fix their own grids..,.

**Comment by LordTylus** [comment]
Has my full support
I would also attemt to code it myself but I dont exactly know how to copy a grid.

I could register a new command which is easy,
get the grid, and do some checks for if it has connections to something, if there ar players in cockpits or cryopids that would blocks the grid from being oasted, delete it and then just paste it back

but the copy part is what I really dont know how to do

**Comment by benjhook** [comment]
This was implemented in a third party plugin.
