### ISSUE TITLE
Request: !summon command

### ISSUE THREAD

**Issue by benjhook** [TorchAPI/Essentials#84]
Requesting a "!summon" command that can be used to summon various in game events/NPCs by admins at their location (or spectator location), regardless of world settings. This could be added to over time but at first I would suggest...

`!summon meteorstorm`
`!summon eclipse 60` (sun goes dark for a period of set seconds - is this possible?)
`!summon unknownsignal`
`!summon cargoship`
`!summon pirate`
`!summon wolf`
`!summon spider`

If admin location isn't determinable, allow the command to also accept XYZ co-ordinates at the end and a range (in km) as a variable for how far away the summoned thing should appear from those co-ordinates (to add a bit of randomness to it and make this viable as a votable command)

**Comment by Kothe** [comment]
If admin location isn't determinable, allow the command to also accept XYZ co-ordinates at the end and a range (in km) for how far away the summoned thing could appear from those co-ordinates (to add a bit of randomness to it and make this viable as a votable command)
