### ISSUE TITLE
Request: NewUserMotdURL

### ISSUE THREAD

**Issue by benjhook** [TorchAPI/Essentials#88]
Requesting a NewUserMotdURL textbox just below the MotdURL textbox that functions like the NewUserMotd (only opens the specified URL for a new user on the server). This would be useful for directing new users to community Discord servers and the like without spamming existing users every time they connect to the server.

**Comment by N1Ran** [comment]
🤔

**Comment by N1Ran** [comment]
After the update I'm afraid

**Comment by benjhook** [comment]
This was implemented in a previous patch.
