### ISSUE TITLE
Config not saving automatically

### ISSUE THREAD

**Issue by Mr-Mors** [TorchAPI/Essentials#90]
There has been a few times I have had items not save while editing Essentials. It would be nice to have a save button. Currently I just add and delete a command when I'm done to force a refresh and a save. This save button does not need to tell the running server that a change has happened just save the file.

**Comment by rexxar-tc** [comment]
No save button.

Which items are not being saved correctly? Something isn't correctly hooked up to send the save notification.

**Comment by Mr-Mors** [comment]
I'll pay more attention. Problem is I've lost work so many times I just always add and remove a row now incase. It had to deal with editing AutoCommands. If no one else is having this issue maybe it was user error.
