### ISSUE TITLE
Helpme! !cleanup hasdisplayname:grid in essentials Server extender

### ISSUE THREAD

**Issue by AlienEsp** [TorchAPI/Essentials#99]
Hi, I do not know how to clean by grid name. Previously I did it in server extender with delete hasdisplayname: grid, I can not find the way to do it now.

Thanks...

**Comment by Jimmacle** [comment]
`!cleanup delete name <put regex here>`

**Comment by AlienEsp** [comment]
> `!cleanup delete name <put regex here>`

but this erases the exact name, I need it to be contained in the name

**Comment by Jimmacle** [comment]
It doesn't erase the exact name, it deletes grids with names that match the regular expression you provide.

https://www.mikesdotnetting.com/article/46/c-regular-expressions-cheat-sheet

**Comment by AlienEsp** [comment]
Thank you very much, I found it. I am the administrator of a Spanish server without programming knowledge and I want you to know that we appreciate it very much, thanks again, I learn a lot
